name: Run `main.py` every two weeks

on:
  schedule:
    # Run every two weeks on Monday at 00:00 UTC (01:00 UTC+1)
    - cron: "0 0 */14 * *"
  push:
    branches:
      - master

jobs:
  run_main:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install any dependencies if necessary
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      # Run the script
      - name: Run `main.py`
        run: python3 main.py
