name: Clean up playlists

on:
  schedule:
    # Run every two weeks on Monday at 00:00 UTC
    - cron: "0 0 */14 * *"
  push:
    branches:
      - main
      - master

jobs:
  run_main:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Run `main.py`
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
        run: |
          python3 main.py
